let stockProductos = [
  {
    id: 1,
    nombre: 'Buzo 1',
    categoria: 'buzo',
    cantidad: 1,
    desc: 'Un buzo que re va con vos',
    precio: 1200,
    img: '../img/microfono.jpg',
  },
  {
    id: 2,
    nombre: 'Buzo 2',
    categoria: 'buzo',
    cantidad: 1,
    desc: 'Un buzo que re va con vos',
    precio: 1100,
    img: '../img/microfono.jpg',
  },
  {
    id: 3,
    nombre: 'Buzo 3',
    categoria: 'buzo',
    cantidad: 1,
    desc: 'Un buzo que re va con vos',
    precio: 1200,
    img: '../img/microfono.jpg',
  },
  {
    id: 4,
    nombre: 'Buzo 4',
    categoria: 'buzo',
    cantidad: 1,
    desc: 'Un buzo que re va con vos',
    precio: 1400,
    img: '../img/microfono.jpg',
  },
  {
    id: 5,
    nombre: 'Buzo 5',
    categoria: 'buzo',
    cantidad: 1,
    desc: 'Un buzo que re va con vos',
    precio: 1200,
    img: '../img/microfono.jpg',
  },
  {
    id: 6,
    nombre: 'Buzo 6',
    categoria: 'buzo',
    cantidad: 1,
    desc: 'Un buzo que re va con vos',
    precio: 1500,
    img: '../img/microfono.jpg',
  },
  {
    id: 7,
    nombre: 'Remera 1',
    categoria: 'remera',
    cantidad: 1,
    desc: 'Una remera que re va con vos',
    precio: 500,
    img: '../img/monitor.jpg',
  },
  {
    id: 8,
    nombre: 'Remera 2',
    categoria: 'remera',
    cantidad: 1,
    desc: 'Una remera que re va con vos',
    precio: 500,
    img: '../img/monitor.jpg',
  },
  {
    id: 9,
    nombre: 'Remera 3',
    categoria: 'remera',
    cantidad: 1,
    desc: 'Una remera que re va con vos',
    precio: 500,
    img: '../img/monitor.jpg',
  },
  {
    id: 10,
    nombre: 'Remera 4',
    categoria: 'remera',
    cantidad: 1,
    desc: 'Una remera que re va con vos',
    precio: 700,
    img: '../img/monitor.jpg',
  },
  {
    id: 11,
    nombre: 'Remera 5',
    categoria: 'remera',
    cantidad: 1,
    desc: 'Una remera que re va con vos',
    precio: 700,
    img: '../img/monitor.jpg',
  },
  {
    id: 12,
    nombre: 'Remera 6',
    categoria: 'remera',
    cantidad: 1,
    desc: 'Una remera que re va con vos',
    precio: 700,
    img: '../img/monitor.jpg',
  },
  {
    id: 13,
    nombre: 'Camisa 1',
    categoria: 'camisa',
    cantidad: 1,
    desc: 'Una camisa que re va con vos',
    precio: 900,
    img: '../img/mouse.jpeg',
  },
  {
    id: 14,
    nombre: 'Camisa 2',
    categoria: 'camisa',
    cantidad: 1,
    desc: 'Una camisa que re va con vos',
    precio: 1400,
    img: '../img/mouse.jpeg',
  },
  {
    id: 15,
    nombre: 'Camisa 3',
    categoria: 'camisa',
    cantidad: 1,
    desc: 'Una camisa que re va con vos',
    precio: 7000,
    img: '../img/mouse.jpeg',
  },
  {
    id: 16,
    nombre: 'Camisa 4',
    categoria: 'camisa',
    cantidad: 1,
    desc: 'Una camisa que re va con vos',
    precio: 777,
    img: '../img/mouse.jpeg',
  },
  {
    id: 17,
    nombre: 'Camisa 5',
    categoria: 'camisa',
    cantidad: 1,
    desc: 'Una camisa que re va con vos',
    precio: 234,
    img: '../img/mouse.jpeg',
  },
  {
    id: 18,
    nombre: 'Camisa 6',
    categoria: 'camisa',
    cantidad: 1,
    desc: 'Una camisa que re va con vos',
    precio: 155600,
    img: '../img/mouse.jpeg',
  },
  {
    id: 19,
    nombre: 'Pantalon 1',
    categoria: 'pantalon',
    cantidad: 1,
    desc: 'Una pantalon que re va con vos',
    precio: 1600,
    img: '../img/teclado.jpg',
  },
  {
    id: 20,
    nombre: 'Pantalon 2',
    categoria: 'pantalon',
    cantidad: 1,
    desc: 'Una pantalon que re va con vos',
    precio: 3200,
    img: '../img/teclado.jpg',
  },
  {
    id: 21,
    nombre: 'Pantalon 3',
    categoria: 'pantalon',
    cantidad: 1,
    desc: 'Una pantalon que re va con vos',
    precio: 2300,
    img: '../img/teclado.jpg',
  },
  {
    id: 22,
    nombre: 'Pantalon 4',
    categoria: 'pantalon',
    cantidad: 1,
    desc: 'Una pantalon que re va con vos',
    precio: 5600,
    img: '../img/teclado.jpg',
  },
  {
    id: 23,
    nombre: 'Pantalon 5',
    categoria: 'pantalon',
    cantidad: 1,
    desc: 'Una pantalon que re va con vos',
    precio: 1700,
    img: '../img/teclado.jpg',
  },
  {
    id: 24,
    nombre: 'Pantalon 6',
    categoria: 'pantalon',
    cantidad: 1,
    desc: 'Una pantalon que re va con vos',
    precio: 800,
    img: '../img/teclado.jpg',
  },
];
